#!python

import logging

from gui import gui  # noqa: I900


class CustomFormatter(logging.Formatter):

    grey = "\x1b[38;20m"
    yellow = "\x1b[33;20m"
    red = "\x1b[31;20m"
    bold_red = "\x1b[31;1m"
    reset = "\x1b[0m"
    message = "%(levelname)s: %(message)s"

    FORMATS = {
        logging.DEBUG: grey + message + reset,
        logging.INFO: grey + message + reset,
        logging.WARNING: yellow + message + reset,
        logging.ERROR: red + message + reset,
        logging.CRITICAL: bold_red + message + reset,
    }

    def format(self, record):
        log_fmt = self.FORMATS.get(record.levelno)
        formatter = logging.Formatter(log_fmt)
        return formatter.format(record)


# TODO: Set this in command line argument
# If you want to be spammed less choose a different logging level:
# DEBUG
# INFO
# WARNING
# ERROR
# CRITICAL

# create logger with 'spam_application'
logger = logging.getLogger("Frog")
logger.setLevel(logging.DEBUG)

# create console handler with a higher log level
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
ch.setFormatter(CustomFormatter())
logger.addHandler(ch)


gui.main()
